

-- Table CLIENTE
CREATE TABLE CLIENTE 
(
    IDCLI NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOMCLI varchar2(20),
    APEPCLI varchar2(40),
    APEMCLI varchar2(40),
    DNICLI char(8),
    TELCLI char(9),
    GMLCLI varchar2(30),
    ESTCLI char(1) DEFAULT 'A' ,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (IDCLI)
) ;

-- INSERT INTO CLIENTE
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Joel', 'Mamani','Quispe','77436585','963214587','Joel@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Jose', 'Torres','Sanches','22455689','987456123','Jose@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Paul' , 'Quispe','Meneses','78965321','951236478','Paul@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('jose' ,'Asuncion','Comas','74852396','985632147','Jose@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Cecilia' ,'Caceres','Lornejo','75214596','963214785','Cecilia@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Esteban' ,'Rigoberto','Alta','76325894','987563214','Esteban@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Macarena' ,'Bautista','Paucar','75315982','987451263','Macarena@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Jeremias' ,'Pantano','Aguila','25413698','978456123','Jeremias@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Aria' ,'Hurtado','Huerta','23456987','951427863','Aria@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Luz','Olivares','Carrera','15591061','951159863','olivares@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Alejandra','Mallqui','Barreto','15600378','952589863','mallqui@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Blanca','Coca','Naturalich','15600983','952753863','coca@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Sonia','Obispo','Gavino','15601549','952745863','obispo@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Katy','Ly','Albujar','15672355','952742583','ly@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Cele','Aleman','Cruz','15723366','952325863','aleman@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Carlos','Gabino','Dias','15726079','952736563','gabino@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Eva','Trujillo','Alejo','15757378','952745965','trujillo@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Silas','Leon','Espinoza','15942236','954125863','leon@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Deysi','Salazar','Garcia','16416033','958545863','salazar@gmail.com');
INSERT INTO CLIENTE (NOMCLI, APEPCLI,APEMCLI, DNICLI, TELCLI,GMLCLI)VALUES('Pedro' ,'Castle','Gutierres','73156489','932145687','Pedro@gmail.com');
COMMIT;

select * from CLIENTE;

-- Table: COMPRA
CREATE TABLE COMPRA (
    IDCOM NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    IDPRO int  NOT NULL,
    FECCOM date  NOT NULL,
    TIPPAGCOM varchar2(30)  NOT NULL,
    ESTCOM char(1) DEFAULT 'A',
    CONSTRAINT COMPRA_pk PRIMARY KEY (IDCOM)
) ;
INSERT INTO COMPRA (IDPRO, FECCOM, TIPPAGCOM, ESTCOM)VALUES (1, TO_DATE('14/05/2001', 'DD/MM/YY'), 'Efectivo', 'A');
INSERT INTO COMPRA (IDPRO, FECCOM, TIPPAGCOM, ESTCOM)VALUES (2, TO_DATE('15/05/2001', 'DD/MM/YY'), 'Tarjeta',  'A');
INSERT INTO COMPRA (IDPRO, FECCOM, TIPPAGCOM, ESTCOM)VALUES (1, TO_DATE('16/05/2001', 'DD/MM/YY'), 'Transferencia', 'A');
INSERT INTO COMPRA (IDPRO, FECCOM, TIPPAGCOM, ESTCOM)VALUES (3, TO_DATE('17/05/2001', 'DD/MM/YY'), 'Efectivo', 'A');
INSERT INTO COMPRA (IDPRO, FECCOM, TIPPAGCOM, ESTCOM)VALUES (2, TO_DATE('18/05/2001', 'DD/MM/YY'), 'Tarjeta', 'A');

-- Table: COMPRA_DETALLE
CREATE TABLE COMPRA_DETALLE (
    IDCOMDET NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    IDMED int  NOT NULL,
    IDCOM int  NOT NULL,
    CANCOMDET integer  NOT NULL,
    PRECOMDET number(8,2)  NOT NULL,
    CONSTRAINT COMPRA_DETALLE_pk PRIMARY KEY (IDCOMDET)
) ;
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (1, 11, 3, 5.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (2, 12, 2, 4.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (3, 12, 4, 7.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (4, 12, 1, 1.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (1, 13, 2, 3.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (2, 13, 5, 8.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (3, 14, 1, 9.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (4, 14, 3, 4.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (1, 15, 2, 5.00);
INSERT INTO COMPRA_DETALLE (IDMED, IDCOM, CANCOMDET, PRECOMDET)VALUES (2, 15, 4, 6.00);

-- Table: EMPLEADO
CREATE TABLE EMPLEADO (
    IDEMP NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NOMEMP varchar2(40)  NOT NULL,
    APEPEMP varchar2(70)  NOT NULL,
    APEMEMP varchar2(70)  NOT NULL,
    DNIEMP char(8)  NOT NULL,
    USUEMP varchar2(20)  NOT NULL,
    PASEMP varchar2(16)  NOT NULL,
    TELEMP char(9)  NOT NULL,
    ESTEMP char(1) DEFAULT 'A',
    CONSTRAINT EMPLEADO_pk PRIMARY KEY (IDEMP)
) ;

-- INSERT INTO EMPLEADO
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Alma','Asto', 'Atoche','74521365','AlmaAsto','74521365','974687432');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Jett','Robles', 'Zambrano','71456585','JettRobles','71456585','975738742');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Ben','Yucra', 'Casas','76459325','Benyucra','76459325','954783867');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Juan','Oliva','Gustamante','74521222','oliva','74521222','954784447');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Pablo','Vasques', 'Rios','74521332','vasques','74521332','954782247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Luis',' Feijoo','Lama','75521332','feijoo','75528832','953332247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Jaime','silva','Marchan','75444332','silva','75444332','953332247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Ricardo','calmet','Rodriguez','00370639','calmet','00370639','953123247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Manuel','laque','Contreras','00421804','laque','00421804','952343247');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Santos','leon','Franco','00426463','leon','00426463','952312347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Martin','Chumbe','Ruiz','00821661','chumbe','00821661','952147347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Loyta','Lopez','Peña','01004062','lopez','01004062','912347347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Julio','Linarez','Melendez','01221713','linarez','01221713','912236347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Juan','Bernedo','Soto','01230718','bernedo','01230718','914566347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Ruben','Puma','Lopez','01285100','puma','01285100','917896347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Adrian','Sanizo','mamani','01307186','sanizo','01307186','917369347');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Jose','Choque','palli','01309966','choque','01309966','917369852');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Rus','Foraquita','zapana','01315112','foraquita','01315112','917741852');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Elena','Calderon','muños','01323690','calderon','01323690','914561852');
INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)VALUES('Consuelo','Jimenes','Ladrillo','23126545','ConsueloJimenes','23126545','973654236');
COMMIT;

select * from EMPLEADO;

-- Table: MEDICAMENTO
CREATE TABLE MEDICAMENTO (
    IDMED NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    TIPOMED char(1)  NOT NULL,
    NOMMED varchar2(30)  NOT NULL,
    STOMED int  NOT NULL,
    LABMED varchar2(30)  NOT NULL,
    NUMLOTMED varchar2(7)  NOT NULL,
    PREMED DECIMAL(8,2)  NOT NULL,
    FECVENCMED date  NOT NULL,
    CONSTRAINT MEDICAMENTO_pk PRIMARY KEY (IDMED)
) ;

-- INSERT INTO MEDICAMENTO
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Amoxicilina',300,'74521365','2001651','5','15/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Clamoxyl',300,'74521365','2001651','5','15/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Diclofenaco',250,'71456585','2145785','5','20/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Dolotren',250,'71456585','2145785','5','20/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Fluoxetina',200,'76459325','7644512','2','19/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Luramon',200,'76459325','7644512','2','19/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Diazepam',350,'23126545','5643456','3','05/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Valium',350,'23126545','5643456','3','05/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Ibuprofeno',170,'76459326','3705357','2','12/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Espidifen',170,'76459325','3705356','2','12/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Ácido acetilsalicílico',120,'7645932','661523','2','15/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Aspirina',120,'7645932','661523','2','15/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Paracetamol',220,'76459325','2979245','10','09/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Algidol',220,'76459325','2979245','10','09/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Metamizol',180,'76459325','3450709','3','01/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Nolotil',180,'76459325','3450709','3','01/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Lorazepam',210,'76459326','1062269','2','18/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Orfidal',210,'76459327','1062268','2','18/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Clonazepam',150,'76459325','4578120','5','15/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Rivotril',150,'76459325','4578120','5','15/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Tramadol',220,'76459325','0093065','4','20/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Adolonta',220,'76459377','0093066','4','20/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Oxicodona',110,'76459325','2609696','5','22/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','OxyContin',110,'76459325','2609696','5','22/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Indometacina',230,'76459325','6859230','3','09/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Antalgil',230,'76459325','6859231','3','09/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Naproxeno',190,'76459326','0172025','2','08/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Artron',190,'76459325','0172026','2','08/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Piroxicam',200,'76459324','2300038','3','22/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Dixonal',200,'76459310','2300037','3','22/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Meloxicam',180,'76459325','1245637','2','21/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Mobic',180,'76459325','1245637','2','21/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Sulindaco',210,'76459325','4456113','2','07/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Aciclovir',210,'76459325','4456113','2','07/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Entodolaco',190,'76459325','2825634','3','05/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Lodine',190,'76459325','2825634','3','05/12/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Tolmetina',200,'76459324','3681033','2','17/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Tolectin',200,'76459325','3681032','2','17/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('G','Ketorolaco',210,'76459325','1693001','2','16/11/22');
INSERT INTO MEDICAMENTO (TIPOMED,NOMMED, STOMED, LABMED, NUMLOTMED, PREMED,FECVENCMED)VALUES('C','Trometamina',210,'76459325','1693001','2','16/11/22');
COMMIT;

select * from MEDICAMENTO;

-- Table: PROVEEDOR
CREATE TABLE PROVEEDOR (
    IDPRO NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    RAZCOMPRO varchar2(100) ,
    RUCPROV char(11) ,
    EMAPRO varchar2(100) ,
    CELPRO char(9) ,
    DIRPROV varchar2(100) ,
    ESTPROV char(1) DEFAULT 'A',
    CONSTRAINT PROVEEDOR_pk PRIMARY KEY (IDPRO)
) ;

INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('PharmaSolutions','PharmaSolutions S.A. de C.V.','20528125698','PharmaSolutions.c@gmail.com','943731722');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('Salud y Vida','Laboratorios Salud y Vida S.A.','20602574955','LapSalud.@gmail.com','930547850');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('BioTech Pharma','BioTech Pharma','20608339460','Pharma,BioTech@gmail.com','924524929');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('Biocare','Laboratorios Biocare S.A.','20486193809','Biocare.2020@gmail.com','963365369');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('Genética','Farmacéutica Genética S.A.','20425564910','Genetica.g@gmail.com','919591170');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('Innovations','Pharma Innovations S.A. de C.V.' ,'20551164072','Innovations.p@gmail.com','936707150');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('MedPharm','MedPharm Solutions S.A.','20566068584','medpharma.03@gmail.com','900944156');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('Farmacéuticos Unidos','Farmacéuticos Unidos S.A. de C.V.','20107666304','farmauni@gmail.com','945198871');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('PharmaCorp','PharmaCorp S.A.','2052188681','pharmacorp.c@gmail.com','961953813');
INSERT INTO PROVEEDOR(RAZSOCPRO,RAZCOMPRO,RUCPROV,EMAPRO,CELPRO)VALUES ('Novamed','Laboratorios Novamed S.A. de C.V.','20603002971','novamed.19@gmail.com','978475223');

-- Table: VENTA
CREATE TABLE VENTA (
    IDVEN NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    FACVEN varchar2(8)  NOT NULL,
    FECVEN date  NOT NULL,
    ESTVEN char(1) DEFAULT 'A',
    IDEMP int  NOT NULL,
    IDCLI int  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVEN)
) ;

-- INSERT INTO VENTA
INSERT INTO VENTA (FACVEN,FECVEN,IDEMP,IDCLI)VALUES('F0010001','22/04/22','1','1');
INSERT INTO VENTA (FACVEN,FECVEN,IDEMP,IDCLI)VALUES('F0010002','22/05/22','2','2');
INSERT INTO VENTA (FACVEN,FECVEN,IDEMP,IDCLI)VALUES('F0010003','22/03/22','1','3');
COMMIT;

select * from VENTA;

-- Table: VENTA_DETALLE
CREATE TABLE VENTA_DETALLE (
    IDVENDET NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CANMED int  NOT NULL,
    ESTVEND char(1) DEFAULT 'A',
    IDMED int  NOT NULL,
    IDVEN int  NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (IDVENDET)
);
-- INSERT INTO VENTA_DETALLE
INSERT INTO VENTA_DETALLE(CANMED,IDMED,IDVEN)VALUES('3','1','1');
INSERT INTO VENTA_DETALLE(CANMED,IDMED,IDVEN)VALUES('2','2','2');
INSERT INTO VENTA_DETALLE(CANMED,IDMED,IDVEN)VALUES('4','1','3');
COMMIT;

select * from VENTA_DETALLE;

INSERT INTO COMPRA (FACVEN,FECVEN,IDEMP,IDCLI)VALUES('F0010001','22/04/22','1','1');

-- foreign keys
-- Reference: COMPRA_DETALLE_COMPRA (table: COMPRA_DETALLE)
ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_COMPRA
    FOREIGN KEY (IDCOM)
    REFERENCES COMPRA (IDCOM);

-- Reference: COMPRA_DETALLE_MEDICAMENTO (table: COMPRA_DETALLE)
ALTER TABLE COMPRA_DETALLE ADD CONSTRAINT COMPRA_DETALLE_MEDICAMENTO
    FOREIGN KEY (IDMED)
    REFERENCES MEDICAMENTO (IDMED);

-- Reference: COMPRA_PROVEEDOR (table: COMPRA)
ALTER TABLE COMPRA ADD CONSTRAINT COMPRA_PROVEEDOR
    FOREIGN KEY (IDPRO)
    REFERENCES PROVEEDOR (IDPRO);

-- Reference: VENTA_CLIENTE (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES CLIENTE (IDCLI);

-- Reference: VENTA_DETALLE_MEDICAMENTO (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_MEDICAMENTO
    FOREIGN KEY (IDMED)
    REFERENCES MEDICAMENTO (IDMED);

-- Reference: VENTA_DETALLE_VENTA (table: VENTA_DETALLE)
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);

-- Reference: VENTA_EMPLEADO (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_EMPLEADO
    FOREIGN KEY (IDEMP)
    REFERENCES EMPLEADO (IDEMP);

-- VISTA.

CREATE VIEW VENTA_UNIDA AS
SELECT VENTA.IDVEN,VENTA.FACVEN,VENTA.FECVEN,VENTA.IDEMP,VENTA.IDCLI,
VENTA_DETALLE.IDVENDET,VENTA_DETALLE.CANMED,VENTA_DETALLE.IDMED,
UPPER (APEPEMP)|| ' ' || (APEMEMP) || ', ' || NOMEMP AS EMPLEADO,
UPPER (APEPCLI)|| ' ' || (APEMCLI) || ', ' || NOMCLI AS CLIENTE,
MEDICAMENTO.NOMMED AS MEDICAMENTO
FROM VENTA
JOIN VENTA_DETALLE ON VENTA_DETALLE.IDVEN = VENTA.IDVEN
JOIN EMPLEADO ON EMPLEADO.IDEMP=VENTA.IDEMP
JOIN CLIENTE ON CLIENTE.IDCLI=VENTA.IDCLI
JOIN MEDICAMENTO ON MEDICAMENTO.IDMED =VENTA_DETALLE.IDMED;


CREATE VIEW COMPRA_UNIDA AS
SELECT COMPRA.IDCOM, COMPRA.FECCOM, COMPRA.TIPPAGCOM, COMPRA.ESTCOM,
       COMPRA_DETALLE.IDCOMDET, COMPRA_DETALLE.CANCOMDET,
       MEDICAMENTO.IDMED, MEDICAMENTO.NOMMED
FROM COMPRA
JOIN COMPRA_DETALLE ON COMPRA_DETALLE.IDCOM = COMPRA.IDCOM
JOIN MEDICAMENTO ON MEDICAMENTO.IDMED = COMPRA_DETALLE.IDMED;


select * from COMPRA_UNIDA;
select * from VENTA_UNIDA;
select * from VENTA_DETALLE;
select * from VENTA;
select * from MEDICAMENTO;
select * from EMPLEADO;
select * from CLIENTE;
select * from proveedor;
select * from VISTA_COMPRA;
SET SERVEROUTPUT ON


-- Crear el procedimiento
CREATE OR REPLACE PROCEDURE imprimir_mensaje(mensaje IN VARCHAR2) IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('El mensaje es: ' || mensaje);
END;
/

-- Ejecutar el procedimiento
BEGIN
  imprimir_mensaje('¡Hola, mundo!');
END;
/


-----------------------------------
CREATE OR REPLACE PROCEDURE saludar(nombre IN VARCHAR2) IS
BEGIN
  DBMS_OUTPUT.PUT_LINE('¡Hola, ' || nombre || '!');
END;
/
BEGIN
  saludar('Edy');
END;
/

------------------------------------
CREATE OR REPLACE FUNCTION duplicar_valor(num IN INTEGER) RETURN NUMBER AS
    valor_duplicado NUMBER;
BEGIN
    valor_duplicado := num * 2;
    RETURN valor_duplicado;
END;
/
BEGIN
    DBMS_OUTPUT.PUT_LINE('El valor duplicado es: ' || duplicar_valor(30));
END;
/

-- Crear el procedimiento
CREATE OR REPLACE PROCEDURE calcular_suma(
  num1 IN NUMBER,
  num2 IN NUMBER,
  resultado OUT NUMBER
) IS
BEGIN
  resultado := num1 + num2;
END;
/

-- Ejecutar el procedimiento
DECLARE
  resultado_suma NUMBER;
BEGIN
  calcular_suma(10, 5, resultado_suma);
  DBMS_OUTPUT.PUT_LINE('El resultado de la suma es: ' || resultado_suma);
END;
/



----------------------

CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTE(
    p_NOMCLI IN VARCHAR2,
    p_APEPCLI IN VARCHAR2,
    p_APEMCLI IN VARCHAR2,
    p_DNICLI IN CHAR,
    p_TELCLI IN CHAR,
    p_GMLCLI IN VARCHAR2
)
AS
BEGIN
    -- Insertar en la tabla CLIENTE
    INSERT INTO CLIENTE (NOMCLI, APEPCLI, APEMCLI, DNICLI, TELCLI, GMLCLI)
    VALUES (p_NOMCLI, p_APEPCLI, p_APEMCLI, p_DNICLI, p_TELCLI, p_GMLCLI);
    
    -- Confirmar la transacción
    COMMIT;
END;
/
BEGIN
    INSERTAR_CLIENTE(
        'Dane',       -- p_NOMCLI
        'Ramirez',        -- p_APEPCLI
        'Smith',      -- p_APEMCLI
        '98224672',   -- p_DNICLI
        '992563224',  -- p_TELCLI
        'dane@gmail.com'  -- p_GMLCLI
    );
    COMMIT;
END;


-- Crear procedimiento
CREATE OR REPLACE PROCEDURE INSERTAR_CLIENTE_EMPLEADO(
    p_NOMCLI IN VARCHAR2,
    p_APEPCLI IN VARCHAR2,
    p_APEMCLI IN VARCHAR2,
    p_DNICLI IN CHAR,
    p_TELCLI IN CHAR,
    p_GMLCLI IN VARCHAR2,
    p_NOMEMP IN VARCHAR2,
    p_APEPEMP IN VARCHAR2,
    p_APEMEMP IN VARCHAR2,
    p_DNIEMP IN CHAR,
    p_USUEMP IN VARCHAR2,
    p_PASEMP IN VARCHAR2,
    p_TELEMP IN CHAR
)
AS
BEGIN
    -- Insertar en la tabla CLIENTE
    INSERT INTO CLIENTE (NOMCLI, APEPCLI, APEMCLI, DNICLI, TELCLI, GMLCLI)
    VALUES (p_NOMCLI, p_APEPCLI, p_APEMCLI, p_DNICLI, p_TELCLI, p_GMLCLI);
    
    -- Insertar en la tabla EMPLEADO
    INSERT INTO EMPLEADO (NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP)
    VALUES (p_NOMEMP, p_APEPEMP, p_APEMEMP, p_DNIEMP, p_USUEMP, p_PASEMP, p_TELEMP);
    
    -- Confirmar la transacción
    COMMIT;
END;
/

BEGIN
    INSERTAR_CLIENTE_EMPLEADO(
        'John',       -- p_NOMCLI
        'Doe',        -- p_APEPCLI
        'Smith',      -- p_APEMCLI
        '12345678',   -- p_DNICLI
        '123456789',  -- p_TELCLI
        'john@example.com',  -- p_GMLCLI
        'Jane',       -- p_NOMEMP
        'Doe',        -- p_APEPEMP
        'Smith',      -- p_APEMEMP
        '87654321',   -- p_DNIEMP
        'jane_user',  -- p_USUEMP
        'password',   -- p_PASEMP
        '987654321'   -- p_TELEMP
    );
    COMMIT;
END;




























select IDEMP, NOMEMP, APEPEMP, APEMEMP, DNIEMP, USUEMP, PASEMP, TELEMP, ESTEMP from EMPLEADO;

SELECT NOMEMP FROM EMPLEADO WHERE NOMEMP LIKE '%' ||  1   || '%';

